-- RECURSO CREADO PARA EL SERVIDOR RP DESPERADOSRP.COM --
-- Implementado por Mapachito --
1. /orinar.
SI UTILIZAS EL RECURSO, MENCIONAME Y CONTRIBUYE A QUE LA COMUNIDAD ESPAÑOLA DE REDM CREZCA ;)

A disfrutarlo!!

VERSIÓN 1.0 17-08-2020
